#!/usr/bin/env bash

usage()
{
    echo "usage: pull_all [[-c] [-b] | [-h] | [-y]]"
}

continue_on_error=0
run_bundle_check=0
run_yarn_check=0

while [ "$1" != "" ]; do
    case $1 in
        -b | --bundle )         run_bundle_check=1
                                ;;
        -c | --continue )       continue_on_error=1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        -y | --yarn )           run_yarn_check=1
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done


if [ $continue_on_error -eq 0 ]; then
    set -e
fi


dirs=()

dirs+=(~/projects/pmpaware/autolicensing-api/)
dirs+=(~/projects/pmpaware/pmpaware-coherence/)
dirs+=(~/projects/pmpaware/pmpaware-consolidation/)
dirs+=(~/projects/pmpaware/pmpaware-database/)
dirs+=(~/projects/pmpaware/pmpaware-export/)
dirs+=(~/projects/pmpaware/pmpaware-migration/)
# dirs+=(~/projects/pmpaware/pmpaware-sam-gem/)
dirs+=(~/projects/pmpaware/pmpaware-test/)
dirs+=(~/projects/pmpaware/pmpaware-webapp/)
dirs+=(~/projects/pmpaware/pmpaware_sam/)


for d in ${dirs[*]}
do
    pushd $d 1>/dev/null
    printf "\n********************************************************************************\n"
    pwd
    printf "********************************************************************************\n"

    branch=$(git rev-parse --abbrev-ref HEAD)
    git pull

    if [ $branch != "develop" ] && [ $branch != "master" ]; then
        echo Current Branch: $branch
    fi

    if [ $run_bundle_check -eq 1 ]; then
        if [ -f Gemfile ]; then
            bundle check

            if [ $? -ne 0 ]; then
                bundle install
            fi
        fi
    fi

    if [ $run_yarn_check -eq 1 ]; then
        if [ -f yarn.lock ]; then
            bundle exec yarn check

            if [ $? -ne 0 ]; then
                bundle exec yarn install
            fi
        fi
    fi

    popd 1>/dev/null
done


